version: 2

jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - restore_cache:
          key: terraform-cache-golang
      - run: bash .circleci/dependencies.sh
      - save_cache:
          key: terraform-cache-golang
          paths:
            - ~/terraform
      - run: bash .circleci/testing.sh
